### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by ITyjkai1995** [inkscope/inkscope#109]
Does RPM support Ceph10.2?
Our operating environment:

linux CentOS 7.4.1708 
Ceph version 10.2.9
Apache/2.4.6 
mongodb version v2.6.12
inkscope version: inkscope-admviz-1.4.0-2.centos7.noarch.rpm 

Python Package lists:
```
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
boto (2.34.0)
ceph-deploy (1.5.39)
ceph-detect-init (1.0.1)
ceph-disk (1.0.0)
cephfs (0)
chardet (2.2.1)
configobj (4.7.2)
decorator (3.4.0)
Flask (0.10.1, /usr/lib/python2.7/site-packages)
Flask-Login (0.4.1)
iniparse (0.4)
itsdangerous (0.23)
Jinja2 (2.7.2)
kitchen (1.1.1)
Magic-file-extensions (0.2)
MarkupSafe (0.11)
perf (0.1)
pip (9.0.3)
psutil (2.2.0)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pymongo (2.5.2)
python-dateutil (1.5)
python-linux-procfs (0.4.9)
pyudev (0.15)
pyxattr (0.5.1)
rados (0)
rbd (0)
requests (2.6.0)
rsa (3.1.1)
s3cmd (2.0.1)
schedutils (0.4)
setuptools (0.9.8)
simplejson (3.3.3)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
urlgrabber (3.10)
urllib3 (1.10.2)
Werkzeug (0.9.1)
yum-metadata-parser (1.1.4)
```
We installed the RPM package you provided and we found some errors.

```[Mon Apr 16 15:39:55.550662 2018] [:error] [pid 13977] [client 192.168.1.100:52435] Traceback (most recent call last):, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550742 2018] [:error] [pid 13977] [client 192.168.1.100:52435]   File "/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi", line 13, in <module>, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550845 2018] [:error] [pid 13977] [client 192.168.1.100:52435]     from inkscopeCtrlcore import app as application, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550955 2018] [:error] [pid 13977] [client 192.168.1.100:52435]   File "/var/www/inkscope/inkscopeCtrl/inkscopeCtrlcore.py", line 163, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550973 2018] [:error] [pid 13977] [client 192.168.1.100:52435]     deg load_token(token):, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550984 2018] [:error] [pid 13977] [client 192.168.1.100:52435]       ^, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:39:55.550995 2018] [:error] [pid 13977] [client 192.168.1.100:52435] SyntaxError: invalid syntax, referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:40:00.549434 2018] [:error] [pid 12278] [client 192.168.1.100:52438] mod_wsgi (pid=12278): Target WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi' cannot be loaded as Python module., referer: http://192.168.1.12:8080/inkscopeViz/index.html
[Mon Apr 16 15:40:00.549605 2018] [:error] [pid 12278] [client 192.168.1.100:52438] mod_wsgi (pid=12278): Exception occurred processing WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi'., referer: http://192.168.1.12:8080/inkscopeViz/index.html
```

**Comment by A-Dechorgnat** [comment]
Hi
No, RPM package doesn't support Ceph 10.2.
Moreover, we abandon RPM and debian packages in favor of an ansible playbook.
We're trying to have it for the end of next week.

**Comment by A-Dechorgnat** [comment]
Hi,
Ansible playbook is now available at [https://github.com/inkscope/inkscope-ansible](https://github.com/inkscope/inkscope-ansible)
