### ISSUE TITLE
Cephprobe throws TypeError 

### ISSUE THREAD

**Issue by stuartbfox** [inkscope/inkscope#43]
Im trying to run cephprobe on the same server as admviz and ceph-rest-api (ubuntu 14.10 server) and get this error constantly. There are 5 nodes in the ceph cluster (192.168.95.20{1,3.4.5.6}). As you can see from the logs, only hosts 192.168.87.201/206 are causing problems. Any ideas?

2015-03-25 20:17:22.610707 -- WARNING : process_osd_dump did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:24.518298 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 273, in process_status
    monneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:24.566657 -- WARNING : process_status did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:25.611477 -- Process OSDDump
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 364, in process_osd_dump
    osdneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:25.666253 -- WARNING : process_osd_dump did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:27.567115 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 273, in process_status
    monneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:27.615223 -- WARNING : process_status did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:28.667137 -- Process OSDDump
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 364, in process_osd_dump
    osdneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:28.728266 -- WARNING : process_osd_dump did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:30.615837 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 273, in process_status
    monneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:30.690641 -- WARNING : process_status did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:31.729127 -- Process OSDDump
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 364, in process_osd_dump
    osdneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:31.789746 -- WARNING : process_osd_dump did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206'' 
2015-03-25 20:17:33.691415 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 273, in process_status
    monneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:33.743624 -- WARNING : process_status did not worked :  database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.201'' 
2015-03-25 20:17:34.791043 -- Process OSDDump
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 612, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 364, in process_osd_dump
    osdneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 721, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.95.206''

**Comment by stuartbfox** [comment]
Once I dropped the database things worked

**Comment by xiling** [comment]
U can check whethe the host "192.168.95.206" install the sysprobe ,if u do, check it supports the system command "lshw -json" or not.
