### ISSUE TITLE
inkscopeCtrl barfs on large pg maps

### ISSUE THREAD

**Issue by stuartbfox** [inkscope/inkscope#44]
Hi

So Im having a problem when GET /api/v0.1/pg/stat.json returns a large amount of data.
Ive run ceph-rest-api in standalone and wsgi mode with WSGIChunkedRequest On and off.

As you can see, the return size is 14mb
```
time wget http://localhost:5000/api/v0.1/pg/stat.json
--2015-03-25 23:03:10--  http://localhost:5000/api/v0.1/pg/stat.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14618420 (14M) [application/json]
Saving to: ‘stat.json’

100%[====================================================================================================================================================================================================>] 14,618,420  --.-K/s   in 0.02s   

2015-03-25 23:03:11 (565 MB/s) - ‘stat.json’ saved [14618420/14618420]


real	0m1.460s
user	0m0.008s
sys	0m0.022s
```

Logs from ceph-admin-api indicate its a socket.py write buffer/broken pipe error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
192.168.87.20 - - [25/Mar/2015 22:58:08] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:08] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:08] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:08] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:12] "GET /api/v0.1/pg/stat.json HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
192.168.87.20 - - [25/Mar/2015 22:58:18] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:18] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:18] "GET /api/v0.1/status.json HTTP/1.1" 200 -
192.168.87.20 - - [25/Mar/2015 22:58:18] "GET /api/v0.1/status.json HTTP/1.1" 200 -
```

And from the apache logs
```
mod_wsgi (pid=9059): Exception occurred processing WSGI script '/var/www/inkscope/inkscopeCtrl/ceph-rest-api.wsgi'
IOError: failed to write data, referer:
```

**Comment by A-Dechorgnat** [comment]
/api/v0.1/pg/stat.json returns nearly 1.5Kb per pg. It is really too verbose for our purpose.
I'm going to change this call by something else.

If this is blocking for (and I think it is), you can edit the file inkscopeViz/scripts/statusApp.js:
At line 61, change 

    //refresh data every x seconds
    refreshData();
    refreshPGData();
    setInterval(function () {
        refreshData()
    }, 5 * 1000);
    setInterval(function () {
         refreshPGData()
    }, 10 * 1000);

by

    //refresh data every x seconds
    refreshData();
    // refreshPGData();
    setInterval(function () {
        refreshData()
    }, 5 * 1000);
    /* setInterval(function () {
         refreshPGData()
    }, 10 * 1000); */

The impact is just that clean and unclean pools will not be counted.

**Comment by stuartbfox** [comment]
That explains it, I have 32Tb and 8000+ pg's :)
The fix worked for now, thanks for the fast reply

**Comment by A-Dechorgnat** [comment]
Just reopen to follow the fix.

**Comment by A-Dechorgnat** [comment]
Last commit f2274593d138a3276684b4f785def61dff1aa744 should fix that

**Comment by stuartbfox** [comment]
That commit did fix the issue, thanks!
