### ISSUE TITLE
cephprobe won't start

### ISSUE THREAD

**Issue by ingardm** [inkscope/inkscope#48]
python /opt/inkscope/bin/cephprobe.py start

2015-03-28 14:46:02.259627 -- CephProbe loading
clusterName =  ceph
ceph_conf =  /etc/ceph/ceph.conf
ceph_rest_api =  10.0.70.27:5000
ceph_rest_api_subfolder =
fsid =  ef210584-31a8-4d1d-a50f-5f0f5be6cc6d
hb_refresh =  5
status_refresh =  3
osd_dump_refresh =  3
pg_dump_refresh =  60
crushmap_refresh =  60
df_refresh =  60
cluster_window =  1200
osd_window =  1200
pool_window =  1200
mongodb_host =  10.0.70.27
mongodb_port =  27017
is_mongo_replicat =  0
mongodb_set =  'mongodb0:27017,mongodb1:27017,mongodb2:27017'
mongodb_replicaSet =  replmongo0
mongodb_read_preference =  ReadPreference.SECONDARY_PREFERRED
is_mongo_authenticate 0
mongodb_user =  ceph
mongodb_passwd =  monpassword
no replicat set
no authentication
2015-03-28 14:46:02.278904 -- Process Status
2015-03-28 14:46:02.325339 -- Process Crushmap
2015-03-28 14:46:02.405690 -- Process OSDDump
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 714, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "/opt/inkscope/bin/cephprobe.py", line 643, in run
    init_cluster(restapi, ceph_rest_api_subfolder, db)
  File "/opt/inkscope/bin/cephprobe.py", line 143, in init_cluster
    process_osd_dump(restapi, ceph_rest_api_subfolder, db)
  File "/opt/inkscope/bin/cephprobe.py", line 292, in process_osd_dump
    osdneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 604, in find_one
    for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 904, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 848, in _refresh
    self.__uuid_subtype))
  File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 800, in __send_message
    self.__uuid_subtype)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 100, in _unpack_response
    error_object["$err"])
pymongo.errors.OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''10.0.100.1''

**Comment by A-Dechorgnat** [comment]
please look at #43 to see if this helps

**Comment by stuartbfox** [comment]
I was getting them, only way to clear the error was to drop the collections in Mongo. Far from ideal but it got me going again

mongo YOR_HOST
use YOUR_CEPH_CLUSER_NAME
db.getCollectionNames().forEach(function(c) { if(c != 'system.indexes') { db.getCollection(c).drop(); } });

**Comment by ingardm** [comment]
I ended up deleting all mongo data to get it up and running again. All good now :)

**Comment by A-Dechorgnat** [comment]
looking for a possible sequencing issue between ceph and sys probe

**Comment by A-Dechorgnat** [comment]
not reproduced
