### ISSUE TITLE
cephprobe fails with ceph 0.94

### ISSUE THREAD

**Issue by A-Dechorgnat** [inkscope/inkscope#53]
When processing PG Dump:
''
2015-07-01 13:25:01.205015 -- Process Crushmap
2015-07-01 13:25:01.330299 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 613, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 440, in process_pg_dump
    scs = pg['stat_cat_sum']
KeyError: 'stat_cat_sum'
2015-07-01 13:25:02.344241 -- WARNING : process_pg_dump did not worked :  'stat_cat_sum'
2015-07-01 13:25:04.243403 -- Process OSDDump
''

It appears that
-	'stat_cat_sum' doesn't appear in 0.94 , 'stat_sum' exists and is feed
-	'stat_cat_sum' appears in 0.80 nut is an empty object, 'stat_sum' exists and is feed
no 0.72 available to test with.

**Comment by A-Dechorgnat** [comment]
fixed
