### ISSUE TITLE
Many trouble or I'm newby

### ISSUE THREAD

**Issue by RealVaVa** [inkscope/inkscope#99]
debian 8 amd64
python 2.7.9, pip, ceph-deploy, psutil (try to psutil==2.1.3 ),  python-dev, flask-login, simple-json
mongoDB 3.4
Inkscope 1.4.2 (istalled with dpkg  -i *.deb)
lshw sysstat

My ceph_api running with nohup ceph-rest-api -i admin& (on port 5000). Help-page http://192.168.24.20:5000/api/v0.1 is accesible.
I try to install inkscope like wsgi-app on apache 2.4 (like default page)

    ServerAdmin webmaster@localhost

    DocumentRoot /home/inkscope/inkscope
    <Directory "/home/inkscope/inkscope">
    allow from all
    Options None
    Options Indexes FollowSymLinks MultiViews
    Require all granted
    AllowOverride All
    </Directory>
    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
       allow from all
       Options None
       Options Indexes FollowSymLinks MultiViews
       Require all granted
      AllowOverride All
    </Directory>
 
     WSGIScriptAlias /inkscopeCtrl /home/inkscope/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi
    <Directory "/home/inkscope/inkscope/inkScopeCtrl">
     allow from all
     Options None
    Options Indexes FollowSymLinks MultiViews
    Require all granted
     AllowOverride All
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    RewriteEngine On
    RewriteRule ^/ceph-rest-api/(.*)$ /ceph_rest_api/api/v0.1/$1 [R=301,NC,L]
    WSGIScriptAlias /ceph_rest_api /var/www/inkscope/inkscopeCtrl/ceph-rest-api.wsgi
     <Directory "/var/www/inkscope/inkScopeCtrl">
     Require all granted
    </Directory>

    CustomLog ${APACHE_LOG_DIR}/access.log combined

**inkscope.conf**
{    
    "ceph_conf": "/etc/ceph/ceph.conf",
    "ceph_rest_api": "127.0.0.1:5000",
    "ceph_rest_api_subfolder": "ceph_rest_api",
    "mongodb_host" : "127.0.0.1",
    "mongodb_set" : "mongodb0:27017,mongodb1:27017,mongodb2:27017",
    "mongodb_replicaSet" : "replmongo0",
    "mongodb_read_preference" : "ReadPreference.SECONDARY_PREFERRED",
    "mongodb_port" : 27017,
    "mongodb_user":"ceph",
    "mongodb_passwd":"cephpassword0",
    "is_mongo_authenticate" : 0,
    "is_mongo_replicat" : 0,
    "influxdb_endpoint":"http://influxdb_host:influxdb_port",
    "cluster": "ceph",
    "platform": "",
    "status_refresh": 3,
    "osd_dump_refresh": 3,
    "pg_dump_refresh": 60,
    "crushmap_refresh": 60,
    "df_refresh": 60,
    "cluster_window": 1200,
    "osd_window": 1200,
    "pool_window": 1200,
    "mem_refresh": 60,
    "swap_refresh": 600,
    "disk_refresh": 60,
    "partition_refresh": 60,
    "cpu_refresh": 30,
    "net_refresh": 30,
    "mem_window": 1200,
    "swap_window": 3600,
    "disk_window": 1200,
    "partition_window": 1200,
    "cpu_window": 1200,
    "net_window": 1200,
    "inkscope_root" : "inkscope_host:inkscope_port",
    "radosgw_url": "http://127.0.0.1:80",
    "radosgw_admin": "admin",
    "radosgw_key": "access-key",
    "radosgw_secret": "secret-key"
}

+ troubles with **sysprobe and cephprobe**

2017-06-06 12:05:22.644499 -- _CephProbe loading_
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 874, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "/opt/inkscope/bin/cephprobe.py", line 688, in run
    conf = load_conf()
  File "/opt/inkscope/bin/cephprobe.py", line 51, in load_conf
    data = json.load(datasource)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 3 column 5 (char 50)

**Another log:**

_SysProbe loading_
Traceback (most recent call last):
  File "/opt/inkscope/bin/sysprobe.py", line 845, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "/opt/inkscope/bin/sysprobe.py", line 633, in run
    data = load_conf()
  File "/opt/inkscope/bin/sysprobe.py", line 59, in load_conf
    data = json.load(datasource)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 5 column 2 (char 134)

**Comment by ghisl1** [comment]
HI

if you use wsgi option, you have to stop your ceph-rest-api listenning on port 5000
You have to create a specific virtual host with a dedicated port and have to change inkscope.conf with this endpoint

**Comment by RealVaVa** [comment]
Ok.Thx. I'm going to try now..
 What about SysProbe and Cephprobe logs?
